# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11V-jbgoYq_ZfZn5MDO78xLQXAxPGb83f
"""

import string

"""n = numero di lettere da shiftare

word = parola da codificare

word_d = parola da decodificare

list1 = lista alfabeto
lista2 = lista alfabeto shiftato

dizionario = lettera list1 : lettera list2
"""

def decifrare(word_d):
    dict_alphabet = dict(zip(alphabet_shift, alphabet))

    word = []

    for letter in word_d:
        letter_d = dict_alphabet[letter]
        word.append(letter_d)

    return word

def codificare(word_d):
    dict_alphabet = dict(zip(alphabet, alphabet_shift))

    word = []

    for letter in word_d:
        letter_d = dict_alphabet[letter]
        word.append(letter_d)

    return word

word = input("Parola da decifrare: ").lower()
n = int(input("Caratteri da shiftare: "))

alphabet = list(string.ascii_lowercase)
alphabet_shift = alphabet[n:] + alphabet[:n]

print(''.join(decifrare(word)))

word = input("Parola da cifrare: ").lower()
n = int(input("Caratteri da shiftare: "))

alphabet = list(string.ascii_lowercase)
alphabet_shift = alphabet[n:] + alphabet[:n]

print(''.join(codificare(word)))

print(alphabet)
print(alphabet_shift)





